In [1]:
import gym
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
#from keras.constraints import MaxNorm
import numpy as np
import tensorflow as tf

Using TensorFlow backend.


In [2]:
from keras import backend as K
K.tensorflow_backend._get_available_gpus()

['/gpu:0']

In [9]:
Q_model.trainable_weights

[<tf.Variable 'dense_1/kernel:0' shape=(393, 400) dtype=float32_ref>,
 <tf.Variable 'dense_1/bias:0' shape=(400,) dtype=float32_ref>,
 <tf.Variable 'dense_2/kernel:0' shape=(400, 100) dtype=float32_ref>,
 <tf.Variable 'dense_2/bias:0' shape=(100,) dtype=float32_ref>,
 <tf.Variable 'dense_3/kernel:0' shape=(100, 30) dtype=float32_ref>,
 <tf.Variable 'dense_3/bias:0' shape=(30,) dtype=float32_ref>,
 <tf.Variable 'dense_4/kernel:0' shape=(30, 1) dtype=float32_ref>,
 <tf.Variable 'dense_4/bias:0' shape=(1,) dtype=float32_ref>]

In [2]:
outputTensor = Q_model.output
outputTensor

NameError: name 'Q_model' is not defined

In [1]:
gradz= Q_model.optimizer.get_gradients(Q_model.output, Q_model.trainable_weights)
gradz

NameError: name 'Q_model' is not defined

In [59]:
symb_inputs = (Q_model._feed_inputs + Q_model._feed_targets + Q_model._feed_sample_weights)

In [60]:
f = K.function(symb_inputs, gradz)

In [61]:
x, y, sample_weight = Q_model._standardize_user_data(np.array([np.ones(393)]), np.array([1]))

In [62]:
output_grad = f(x + y + sample_weight)
output_grad[1]

array([ 0.        ,  0.03010107,  0.        ,  0.        ,  0.        ,
       -0.06744777,  0.        ,  0.01444688,  0.        , -0.08535828,
        0.        ,  0.        ,  0.        , -0.01104266, -0.00857625,
       -0.01458818,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.04903401,  0.        ,
       -0.04271406, -0.04338326, -0.02060068, -0.11471491,  0.00557683,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.01898293,  0.        ,  0.04363398,  0.00640103,  0.04530448,
        0.        , -0.06094191,  0.        ,  0.03056537,  0.0403162 ,
       -0.01516498,  0.03751747,  0.        ,  0.        ,  0.06023069,
       -0.11856923, -0.04107057,  0.        ,  0.        , -0.03238331,
        0.03539745,  0.        ,  0.        ,  0.        , -0.16606736,
        0.        ,  0.        ,  0.        ,  0.00408057,  0.        ,
       -0.04672523,  0.07308167,  0.0204699 ,  0.        ,  0.  

In [48]:
len(output_grad)

8

In [53]:
gradients = K.gradients(outputTensor, Q_model.trainable_weights)
gradients

[<tf.Tensor 'gradients_4/dense_1/MatMul_grad/MatMul_1:0' shape=(393, 400) dtype=float32>,
 <tf.Tensor 'gradients_4/dense_1/BiasAdd_grad/BiasAddGrad:0' shape=(400,) dtype=float32>,
 <tf.Tensor 'gradients_4/dense_2/MatMul_grad/MatMul_1:0' shape=(400, 100) dtype=float32>,
 <tf.Tensor 'gradients_4/dense_2/BiasAdd_grad/BiasAddGrad:0' shape=(100,) dtype=float32>,
 <tf.Tensor 'gradients_4/dense_3/MatMul_grad/MatMul_1:0' shape=(100, 30) dtype=float32>,
 <tf.Tensor 'gradients_4/dense_3/BiasAdd_grad/BiasAddGrad:0' shape=(30,) dtype=float32>,
 <tf.Tensor 'gradients_4/dense_4/MatMul_grad/MatMul_1:0' shape=(30, 1) dtype=float32>,
 <tf.Tensor 'gradients_4/dense_4/BiasAdd_grad/BiasAddGrad:0' shape=(1,) dtype=float32>]

In [17]:
sess= tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [54]:
a=sess.run(gradients,feed_dict={Q_model.input:np.array([np.ones(393)])})

In [63]:
(a[1]==output_grad[1]).all()

True

In [67]:
sess.run(Q_model.trainable_weights[0]+Q_model.trainable_weights[0])

array([[-0.10181691, -0.14678726,  0.11265615, ..., -0.00626637,
         0.13517156,  0.1528523 ],
       [-0.13787633, -0.03509741,  0.01275179, ...,  0.07514228,
        -0.11528447, -0.05215812],
       [-0.05484974,  0.16653013, -0.0506051 , ..., -0.02919607,
         0.05797082, -0.05500043],
       ..., 
       [ 0.00910535,  0.13077888, -0.03367345, ...,  0.00305961,
        -0.02718596,  0.11698362],
       [ 0.14146715, -0.03147355, -0.17342916, ..., -0.07037876,
         0.13913012, -0.05963899],
       [ 0.00132263, -0.00769572, -0.14024879, ...,  0.06369181,
        -0.00342265, -0.11407952]], dtype=float32)

In [68]:
sess.run(Q_model.trainable_weights[0])

array([[-0.05090846, -0.07339363,  0.05632807, ..., -0.00313319,
         0.06758578,  0.07642615],
       [-0.06893817, -0.0175487 ,  0.00637589, ...,  0.03757114,
        -0.05764224, -0.02607906],
       [-0.02742487,  0.08326507, -0.02530255, ..., -0.01459803,
         0.02898541, -0.02750022],
       ..., 
       [ 0.00455268,  0.06538944, -0.01683673, ...,  0.00152981,
        -0.01359298,  0.05849181],
       [ 0.07073358, -0.01573677, -0.08671458, ..., -0.03518938,
         0.06956506, -0.0298195 ],
       [ 0.00066131, -0.00384786, -0.0701244 , ...,  0.0318459 ,
        -0.00171132, -0.05703976]], dtype=float32)

In [40]:
tf.constant(0.0, dtype=tf.float32, shape=[393, 1])

<tf.Tensor 'Const:0' shape=(393, 1) dtype=float32>

In [4]:
#Initializing environment
env = gym.make('Humanoid-v2')
So = env.reset()

In [5]:
#Sampling Action Space
A = []
a = 1000
global A_count
A_count  = np.zeros(a)

for _ in range(a):
    A.append(env.action_space.sample())
    
def Resample_action_space(A):
    dropout_rate = 0.3
    sorted_actions = sorted(list(zip(A,A_count.tolist())), key = lambda x:x[1], reverse = True)
    B = [action[0] for action in sorted_actions[0:(int(len(A)*(1-dropout_rate)))]] + [env.action_space.sample() for _ in range(int(len(A)*dropout_rate))]
    return B

In [6]:
#Creating the model for q(S,a)
Q_model = Sequential()
Q_model.add(Dense(400,input_shape = np.append(So,A[0]).shape, activation = 'relu' ))
Q_model.add(Dropout(0.5))
Q_model.add(Dense(100, activation = 'relu'))
Q_model.add(Dropout(0.5))
Q_model.add(Dense(30, activation = 'relu'))
Q_model.add(Dense(1, activation= 'linear'))

#adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
Q_model.compile(loss="mse", optimizer= "sgd")
print(Q_model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 400)               157600    
_________________________________________________________________
dropout_1 (Dropout)          (None, 400)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 100)               40100     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 30)                3030      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 31        
Total params: 200,761
Trainable params: 200,761
Non-trainable params: 0
_________________________________________________________________
None

In [7]:
import tensorflow as tf

In [8]:
K.get_session().graph

In [12]:
writer = tf.summary.FileWriter('logs', K.get_session().graph)
writer.close()

In [ ]:
K.get_session().graph

In [6]:
#The e-greedy policy

def e_greedy_Policy(s, A, q_model):
    
    e = 0.25
    best_action = 0
    best_prediction = q_model.predict(np.array([np.append(s,A[0])]))[0][0]
    
    for i in range(len(A)):
        value_prediction = q_model.predict(np.array([np.append(s,A[i])]))[0][0]
        if(value_prediction > best_prediction):
            best_action = i
            best_prediction = value_prediction
    
    if(np.random.rand() <= e):
        best_action = np.random.randint(len(A))
    
    A_count[best_action] = A_count[best_action] + 1
    return A[best_action]

In [7]:
#Sarsa Parameters
lamb = 0.9
s = So
action = e_greedy_Policy(s, A, Q_model)
number_of_episodes = 0
total_reward=0

In [ ]:
while(True):
    
    #renders action 
    env.render()
    
    #steps
    state, reward, done, info = env.step(action)
    
    #selects new action acording to the policy
    next_action = e_greedy_Policy(state, A, Q_model)
    
    #computes the target for Q approximation
    target = reward + lamb * Q_model.predict(np.array([np.append(state,next_action)]))[0][0]
    
    #adjusts the q value
    Q_model.fit(np.array([np.append(s,action)]) ,  np.array([target]), verbose = 0)
    
    #adjusts new state
    s = state
    action = next_action 
    total_reward = total_reward + reward
    
    if(done):
        
        s = env.reset()
        action = e_greedy_Policy(s, A, Q_model)
        print(total_reward)
        total_reward = 0
        
        #Resample action space
        number_of_episodes = number_of_episodes + 1
        if(number_of_episodes%10==0):
            A = Resample_action_space(A)
            A_count = np.zeros(len(A))

Creating window glfw
206.463829054
197.879013982
238.250681205
188.602331684
211.030268427
127.143803679
295.902933515
135.226601135
189.640702075
156.033264028
197.515957385
149.333236076
189.156653171
219.400361031
178.453329769
164.097633142
170.465751275
186.935924335
179.440679066
237.717590873
216.62663665
275.404220251
284.771333618
196.69664112
199.637703348
144.467563756
141.261157401
141.872460479
208.646941502
134.950457022
127.454302819
110.01343599
196.116311213
135.81673062
146.903501481
201.3691879
282.345181805
232.293030403
136.195056056
303.940964133
260.941011259
251.937294569
138.180874724
108.133493957
232.083607183
284.521872229
149.385396485
222.836404377
294.908659095
130.55487188
155.688666266
192.863683577
269.540136782
179.742761174
191.14197251
131.785184431
142.180671712
178.197897864
248.749404652
170.446809036
155.243246729
148.763373683
164.651015144
127.492656667
120.282017546
146.391861507
324.271057562
108.793663734
305.602166701
99.1198347994
136.922

256.914011034
186.839944666
215.885510116
205.20209765
119.313608262
180.344378299
344.84679582
258.194499367
251.479047086
187.365377045
98.8254213293
180.09310075
212.215955866
162.153794285
187.318058278
237.921129016
230.317113245
195.737172043
206.074938802
153.420402385
225.73550532
217.315109745
228.464208231
219.507751165
178.784113232
99.70410387
204.021937307
129.989286161
237.130530798
123.383877029
232.624222427
195.460517796
124.147840376
163.533114547
168.408570023
234.670874914
292.16934955
364.659397657
128.534251568
246.820755596
172.907526827
170.721404856
245.010423175
249.769000868
143.208098274
232.64169356
338.571891483
223.717911464
171.590473013
224.641155805
126.866579021
279.763577469
115.543166074
198.849539583
240.71622492
140.901380804
194.683435061
311.198625421
205.160289821
210.35284786
258.511848599
188.1746206
240.641059176
213.601164431
144.403299548
159.699908038
181.567863729
148.595113955
287.429661233
181.707509368
214.414257848
300.749940591
325.