In [1]:
import tensorflow as tf

In [2]:
sess = tf.Session()

In [3]:
tf.test.is_gpu_available()

True

In [4]:
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [6]:
sess.run(tf.constant(1))

1

In [4]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/cpu:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1576176139996347097
, name: "/gpu:0"
device_type: "GPU"
memory_limit: 104831385
locality {
  bus_id: 1
}
incarnation: 11509901856908455473
physical_device_desc: "device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0"
]


In [5]:
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

In [6]:
get_available_gpus()

['/gpu:0']

In [221]:
a = tf.Variable(1, dtype = tf.float32)
b = tf.add(a,1)

In [58]:
b = tf.placeholder(tf.float32)
a.assign(a+a)

<tf.Tensor 'Assign_19:0' shape=() dtype=float32_ref>

In [222]:
sess.run(tf.global_variables_initializer())

In [225]:
sess.run(tf.multiply(a,3))

3.0

In [73]:
a.eval(session = sess)

1.0

In [226]:
import gym
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
#from keras.constraints import MaxNorm
import numpy as np
import tensorflow as tf
import gc
import pickle
from keras.models import load_model
from time import time

Using TensorFlow backend.


In [228]:
policy_model_mean = Sequential()
policy_model_mean.add(Dense(100,input_shape =(1,2) ,kernel_initializer='random_uniform', activation = 'relu' ))
policy_model_mean.add(Dropout(0.5))
policy_model_mean.add(Dense(100,kernel_initializer='random_uniform', activation = 'relu'))
policy_model_mean.add(Dropout(0.5))
policy_model_mean.add(Dense(100,kernel_initializer='random_uniform', activation = 'relu'))
policy_model_mean.add(Dropout(0.5))
policy_model_mean.add(Dense(100,kernel_initializer='random_uniform', activation = 'relu'))
policy_model_mean.add(Dropout(0.5))
policy_model_mean.add(Dense(100,kernel_initializer='random_uniform', activation = 'relu'))
policy_model_mean.add(Dropout(0.5))
policy_model_mean.add(Dense( 2,kernel_initializer='random_uniform', activation='linear' ))

adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
policy_model_mean.compile(loss="mse", optimizer= adam)
print("Policy Mean network")
print(policy_model_mean.summary())

Policy Mean network
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1, 100)            300       
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 100)            0         
_________________________________________________________________
dense_2 (Dense)              (None, 1, 100)            10100     
_________________________________________________________________
dropout_2 (Dropout)          (None, 1, 100)            0         
_________________________________________________________________
dense_3 (Dense)              (None, 1, 100)            10100     
_________________________________________________________________
dropout_3 (Dropout)          (None, 1, 100)            0         
_________________________________________________________________
dense_4 (Dense)              (None, 1, 100)            1

In [229]:
def set_weights(model, weights):  
    if(model=='value'):
        i=0
        for layer in value_model.layers:
            if 'dropout' not in layer.name:
                layer.set_weights([weights[i],weights[i+1]])
                i+=2
    elif(model=='policy_mean'):
        i=0
        for layerz in policy_model_mean.layers:
            if 'dropout' not in layerz.name:
                layerz.set_weights([weights[i],weights[i+1]])
                i+=2
                
    elif(model=='policy_std'):
        i=0
        for layerz in policy_model_std.layers:
            if 'dropout' not in layerz.name:
                layerz.set_weights([weights[i],weights[i+1]])
                i+=2
    else:
        print('error')

def get_value_weights():
    weights =[]
    for w in value_model.layers:
        weights+= w.weights
    return weights

def get_policy_weights_mean():
    weights =[]
    for w in policy_model_mean.layers:
        weights+= w.weights
    return weights

def get_policy_weights_std():
    weights =[]
    for w in policy_model_std.layers:
        weights+= w.weights
    return weights


In [232]:
a =get_policy_weights_mean()

In [233]:
sess.run(tf.global_variables_initializer())

In [234]:
a[0].eval(session =sess)

array([[  4.06114571e-02,  -2.75350697e-02,   2.90420093e-02,
         -8.22212547e-03,  -4.05285582e-02,  -2.86595710e-02,
         -4.08780947e-02,  -4.68562618e-02,   4.97548319e-02,
          1.59048922e-02,   4.95816395e-03,  -2.14918982e-02,
          3.81514318e-02,   2.64419243e-03,  -4.45465110e-02,
         -7.68572092e-03,   2.45478265e-02,   2.92639174e-02,
          2.64492147e-02,  -2.28152405e-02,   2.11475156e-02,
          9.70683992e-04,  -2.01600548e-02,  -3.75226252e-02,
          9.38982889e-03,   2.33183838e-02,   3.62570025e-02,
          4.14830483e-02,  -3.64150889e-02,  -2.96419263e-02,
         -6.23989105e-03,   3.82587314e-06,   3.54946293e-02,
          1.30678676e-02,  -4.04610746e-02,   7.54214451e-03,
         -6.75766543e-03,   2.39876658e-03,  -2.12969538e-02,
         -4.60640565e-02,  -4.97313626e-02,   1.52298696e-02,
          4.08340618e-03,  -4.07279842e-02,   4.00523655e-02,
          4.22074646e-03,   3.02755497e-02,   2.49557979e-02,
        

In [254]:
sess.run(a[0].assign(np.zeros(shape=(2,100))))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [238]:
a[0].eval(session = sess)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [239]:
policy_gradients_mean = policy_model_mean.optimizer.get_gradients(policy_model_mean.output, policy_model_mean.trainable_weights)

In [252]:
np.array(sess.run(tf.shape(a[0])))

array([  2, 100])